### ISSUE TITLE
Upscaling doesn't effect the size of new lines 

### ISSUE THREAD

**Issue by Dionicio3** [Epicpkmn11/nftr-editor#3]
It appears when you change the size of the font, it doesn't actually effect new lines
![Screenshot_20221004-191954_Chrome](https://user-images.githubusercontent.com/61460279/193965456-15293ae0-0964-4a12-b217-9a6425bebbc4.png)
![Screenshot_20221004-191943_Chrome](https://user-images.githubusercontent.com/61460279/193965458-2229509a-5632-4555-8f83-a659d8991b3e.png)

**Comment by Epicpkmn11** [comment]
Whoops, that's what I get for writing this on the bus and not testing it well lol. Fixed by b4405b4869b24d6eb636a49f0e31559ed837b7da




PS good song lol
